INSERT INTO gods (godName, godClass, godPower, godPantheon, godAttackType, Difficulty) VALUES 
('Achilles', 'Warrior', 1, 'Greek', 1, 'Average'),
('Agni', 'Mage', 0, 'Hindu', 0, 'Hard'),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, ''),
('', '', 0, '', 0, '');


-- itemPower: TRUE/1 == Physical, FALSE/0 == Magical
-- itemTier: 1 = tier 1, 2 = tier 2, 3 = tier 3, 4 = evolved item, 5 = starter, 6 = relic, 7 = upgraded relic
-- SELECT * FROM `items` WHERE (NOT) colName IS NULL;
-- INSERT INTO items (itemName, itemIndividualPrice, itemTotalPrice, itemTier, itemTree, itemPassive, itemImage, itemKeywords, itemPowerType, itemPower, itemAttackSpeed, itemLifeSteal, itemPercentPen, itemFlatPen, itemCritChance, itemPhysProt, itemMagProt, itemHealth, itemHP5, itemccr, itemMoveSpeed, itemcdr, itemMana, itemMP5, itemOther) VALUES
INSERT INTO `items`(`itemName`, `itemIndividualPrice`, `itemTotalPrice`, `itemTier`, `itemTree`, `itemPassive`, `itemImage`, `itemKeywords`, `itemPowerType`, `itemPower`, `itemAttackSpeed`, `itemLifeSteal`, `itemPercentPen`, `itemFlatPen`, `itemCritChance`, `itemPhysProt`, `itemMagProt`, `itemHealth`, `itemHP5`, `itemccr`, `itemMoveSpeed`, `itemcdr`, `itemMana`, `itemMP5`, `itemOther`) VALUES 
('Iron Mail', 650, 650, 1, 1, '£', 'ItemImages/iron-mail.jpg', 'hlth physProt', 1, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, 75, NULL, null, NULL, NULL, NULL, NULL, NULL),
('Steel Mail', 750, 1400, 2, 1, '£', 'ItemImages/steel-mail.jpg', 'hlth physProt', 1, NULL, NULL, NULL, NULL, NULL, NULL, 20, NULL, 200, NULL, null, NULL, NULL, NULL, NULL, NULL),
('Sovereignty', 700, 2100, 3, 1, 'AURA - Allied gods within 70 units have their Physical Protections increased by 15 and their HP5 increased by 35.', 'ItemImages/sovereignty.jpg', 'hlth physProt, aura', 1, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, 250, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Mystical Mail', 950, 2350, 3, 1, 'AURA - ALL enemies within 25 units are dealt 40 Magical Damage per second.', 'ItemImages/mystical-mail.jpg', 'hlth physProt, aura', 1, NULL, NULL, NULL, NULL, NULL, NULL, 40, NULL, 200, NULL, 20, NULL, NULL, NULL, NULL, NULL),
('Midgardian Mail', 900, 2300, 3, 1, 'PASSIVE - Enemies that successfully land a basic attack on you have their Movement Speed and Attack Speed reduced by 8% for 2 seconds. This effect can stack up to 3 times and can stack with other item slow effects.', 'ItemImages/midgardian-mail.jpg', 'hlth physProt, attSpd Debuff, slow,', 1, NULL, NULL, NULL, NULL, NULL, NULL, 40, NULL, 300, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
("Emperor's Armor", 600, 2000, 3, 1, 'AURA - Damageable enemy structures within 55 units have their Attack Speed reduced by 30%. Damageable allied structures within 55 units have their Attack Speed increased by 40%.', 'ItemImages/emperors-armor.jpg', 'hlth physProt, aura', 1, NULL, NULL, NULL, NULL, NULL, NULL, 50, NULL, 250, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Light Blade', 600, 600, 1, 2, '£', 'ItemImages/light-blade.jpg', 'physPow, attSpd', 1, 5, 10, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
('Balanced  Blade', 605, 1250, 2, 2, '£', 'ItemImages/balanced-blade.jpg', 'physPow, attSpd', 1, 15, 15, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
('Asi', 1300, 2250, 3, 2, 'PASSIVE - If you drop below 35% Health, you gain an additional 30% Physical Lifesteal for 5 seconds. Can only occur once every 15 seconds.', 'ItemImages/asi.jpg', 'physPow, attSpd, physLs, physPenFlat', 1, 20, 25, 20, NULL, 15, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
('The Executioner', 950, 2200, 3, 2, "PASSIVE - Basic Attacks against an enemy reduce your target's Physical Protection by 7% for 3 seconds (max. 3 Stacks).", 'ItemImages/the-executioner.jpg', 'physPow, attSpd, physPenPerc, stack', 1, 35, 25, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Qin's Sais", 1450, 2700, 3, 2, "PASSIVE - On Basic Attack hits, deal Physical Damage equal to 3% of the target's maximum Health. If the target has over 2000 Health, the bonus damage scales up. This effect reaches a maximum of 5% of the targets Maximum Health at 2750 Health.", 'ItemImages/qins-sais.jpg', 'physPow, attSpd, hlthDmg', 1, 40, 20, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
('Tiny Trinket', 550, 550, 1, 3, '£', 'ItemImages/tiny-trinket.jpg', 'magPow, magLs', 2, 20, NULL, 6, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
('Enchanted Trinket', 550, 1100, 2, 3, '£', 'ItemImages/enchanted-trinket.jpg', 'magPow, magLs, hlth', 2, 30, NULL, 12, NULL, NULL, NULL, null, NULL, 100, NULL, null, NULL, NULL, NULL, NULL, NULL),
('Talon Trinket', 850, 1400, 2, 3, '£', 'ItemImages/talon-trinket.jpg', 'magPow, magLs, mana', 2, 60, NULL, 8, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, 100, NULL, NULL),
("Pythagorem's Piece", 1200, 2300, 3, 3, 'AURA - Allied gods within 70 units have their Magical Lifesteal increased by 12% and their Magical Power increased by 30 or their Physical Lifesteal increased by 10% and their physPow increased by 20.', 'ItemImages/pythagorems-piece.jpg', 'magPow, magLs, hlth, magPenPerc, aura', 2, 40, NULL, 12, 10, NULL, NULL, null, NULL, 200, NULL, null, NULL, NULL, NULL, NULL, NULL),
('Soul Gem', 1200, 2300, 3, 3, 'PASSIVE - On successful hit of an Ability you gain 1 stack. At 4 Stacks your next Ability that damages an enemy God will deal bonus damage equal to 30% of your Magical Power to each God hit, and will heal yourself and allies within 20 units for 40% of your Magical Power and will consume the 4 stacks.', 'ItemImages/soul-gem.jpg', 'magPow, magLs, hlth cdr, stack, dmgPercInc', 2, 80, NULL, 12, NULL, NULL, NULL, null, NULL, 150, NULL, null, NULL, 10, NULL, NULL, NULL),
("Bancroft's Talon", 1100, 2500, 3, 3, 'PASSIVE - You gain additional Magical Power and Lifesteal scaled from missing Health. This caps at 100 power and 20% Lifesteal at 25% Health.', 'ItemImages/bancrofts-talon.jpg', 'magPow, magLs, mana', 2, 100, NULL, 15, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, 150, NULL, NULL),
("Typhon's Fang", 1400, 2800, 3, 3, 'PASSIVE - Your Healing obtained from Magical Lifesteal is increased by 30%. Your Magical Power is increased by twice the amount of Magical Lifesteal you have.', 'ItemImages/typhons-fang.jpg', 'magPow, magLs, mana, magPenPerc, healBuff', 2, 70, NULL, 15, 10, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, 200, NULL, NULL),
('Mace', 650, 650, 1, 4, '£', 'ItemImages/mace.jpg', 'physPow', 1, 15, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
('Heavy Mace', 900, 1550, 2, 4, '£', 'ItemImages/heavy-mace.jpg', 'physPow, physPenFlat', 1, 25, NULL, NULL, NULL, 10, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Warrior's Bane", 850, 1500, 2, 4, '£', 'ItemImages/warriors-bane.jpg', 'physPow, physPenPerc', 1, 20, NULL, NULL, 10, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Titan's Bane", 1050, 2550, 3, 4, 'PASSIVE - Your first ability cast gains 20% Physical Penetration. This can only occur once every 10 seconds.', 'ItemImages/titans-bane.jpg', 'physPow, physPenPerc', 1, 40, NULL, NULL, 20, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Brawler's Beat Stick", 800, 2350, 3, 4, 'PASSIVE - Enemies hit by your Abilities have 40% reduced healing for 8 seconds.', 'ItemImages/brawlers-beat-stick.jpg', 'physPow, physPenFlat, antiHeal,', 1, 40, NULL, NULL, NULL, 15, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Jotunn's Wrath", 800, 2350, 3, 4, '£', 'ItemImages/jotunns-wrath.jpg', 'physPow, physPenFlat, mana, cdr', 1, 40, NULL, NULL, NULL, 10, NULL, null, NULL, NULL, NULL, null, NULL, 20, 150, NULL, NULL),
('The Crusher', 850, 2400, 3, 4, 'PASSIVE - Enemies hit by your damaging Abilities take an additional 20 Physical Damage + 15% of your Physical Power over 2s.', 'ItemImages/the-crusher.jpg', 'physPow, physPenFlat, attSpd, dmgPercInc', 1, 30, 20, NULL, NULL, 15, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),

("Morningstar", 600, 600, 1, 5, "£", 'ItemImages/morningstar.jpg', 'physPow, MP5, ', 1, 10, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, 5, NULL),
("Charged Morningstar", 600, 1200, 2, 5, "£", 'ItemImages/charged-morningstar.jpg', 'physPow, MP5, mana', 1, 20, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, 150, 7, NULL),
("Hydra's Star", 600, 1200, 2, 5, "PASSIVE - For 8 seconds after using an ability, your next basic attack will deal an additional 10% damage. The effect can only occur every 3 seconds.", 'ItemImages/hydras-star.jpg', 'physPow, MP5, cdr, dmgPercInc', 1, 20, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, 5, NULL, 7, NULL),
("Transcendence", 1400, 2600, 3, 5, "PASSIVE - You permanently gain 15 Mana per Stack, and receive 5 Stacks for a god kill, and 1 Stack for a minion kill (max. 50 stacks). 3% of your Mana is converted to Physical Power. At 50 stacks this item Evolves, gaining 10% Cooldown Reduction.", 'ItemImages/transcendence.jpg', 'physPow, MP5, mana, stack,', 1, 35, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, 300, 10, NULL),
("Evolved Transcendence", 0, 2600, 3, 5, "PASSIVE - 3% of your Mana is converted to Physical Power.", 'ItemImages/transcendence.jpg', 'physPow, MP5, mana, evolve, cdr', 1, 35, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, 10, 1050, 10, NULL),
("Hydra's Lament", 950, 2150, 3, 5, "PASSIVE - For 8s after using an ability, your next Basic Attack will deal an additional 40% damage. Abilities that function like basic attacks do not benefit from this. This item grants 2.5 MP5 per 10% of your missing Mana.", 'ItemImages/hydras-lament.jpg', 'physPow, MP5, cdr, dmgPercInc', 1, 40, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, 10, NULL, 10, NULL),
("Heartseeker", 1700, 2900, 3, 5, "PASSIVE - Your abilities deal an additional 2% of the targets maximum Health as Physical Damage. If you have over 200 Physical Power, your ability bonus damage scales up. This effect reaches a maximum of 5% Maximum Health damage at 400 Physical Power. Subsequent hits on the same target do 75% bonus damage for the next 3s.", 'ItemImages/heartseeker.png', 'physPow, MP5, mana, physPenPerc, abilityProc', 1, 65, NULL, NULL, 10, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, 200, 20, NULL),
("Dominance", 1300, 2500, 3, 5, "PASSIVE - Your Basic Attacks benefit from an additional 10% Physical Penetration", 'ItemImages/dominance.jpg', 'physPow, MP5, mana, physPenPerc, ', 1, 55, NULL, NULL, 10, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, 200, 20, NULL),
("Boots", 500, 500, 1, 6, "£", 'ItemImages/boots.jpg', 'mvSpd', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, 6, NULL, NULL, NULL, NULL),
("Combat Boots", 400, 900, 2, 6, "£", 'ItemImages/combat-boots.jpg', 'mvSpd, physPow,', 1, 10, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, 12, NULL, NULL, NULL, NULL),
("Warrior Tabi", 700, 1600, 3, 6, "£", 'ItemImages/warrior-tabi.jpg', 'mvSpd, physPow, mana', 1, 40, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, 18, NULL, 100, NULL, NULL),
("Ninja Tabi", 650, 1550, 3, 6, "£", 'ItemImages/ninja-tabi.jpg', 'mvSpd, physPow, mana, attSpd', 1, 20, 25, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, 18, NULL, 100, NULL, NULL),
("Reinforced Greaves", 650, 1550, 3, 6, "PASSIVE - Every time you are damaged by a god you gain a stack that provides 3 Physical and Magical Protections. Stacks up to 7 times, Lasts 6s", 'ItemImages/reinforced-greaves.jpg', 'mvSpd, physPow, hlth ccr, physProt, magProt, stack', 1, 10, NULL, NULL, NULL, NULL, NULL, null, NULL, 150, NULL, 20, 18, NULL, NULL, NULL, NULL),
("Talaria Boots", 700, 1600, 3, 6, "PASSIVE - You gain +20% additional Movement Speed after leaving the Fountain. This effect lasts 7s.", 'ItemImages/talaria-boots.jpg', 'Movement Speed, physPow, MP5', 1, 15, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, 22, NULL, NULL, 15, NULL),
("Shoes", 500, 500, 1, 7, "£", 'ItemImages/shoes.jpg', 'Movement Speed', 2, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, 6, NULL, NULL, NULL, NULL),
("Magic Shoes", 400, 900, 2, 7, "£", 'ItemImages/magic-shoes.jpg', 'Movement Speed, magPow', 2, 20, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, 12, NULL, NULL, NULL, NULL),
("Shoes of the Magi", 650, 1550, 3, 7, "£", 'ItemImages/shoes-of-the-magi.jpg', 'Movement Speed, magPow, mana, magLs, ', 2, 75, NULL, 8, NULL, NULL, NULL, null, NULL, NULL, NULL, null, 18, NULL, 100, NULL, NULL),
("Shoes of Focus", 700, 1600, 3, 7, "£", 'ItemImages/shoes-of-focus.jpg', 'Movement Speed, magPow, mana, cdr', 2, 55, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, 18, 10, 250, NULL, NULL),
("Reinforced Shoes", 650, 1550, 3, 7, "PASSIVE - Every time you are damaged by a god you gain a stack that provides 3 Physical and Magical Protections. Stacks up to 7 times, Lasts 6s", 'ItemImages/reinforced-shoes.png', 'Movement Speed, magPow, hlth ccr, physProt, magProt, stack', 2, 20, NULL, NULL, NULL, NULL, NULL, null, NULL, 150, NULL, 20, 18, NULL, NULL, NULL, NULL),
("Traveler's Shoes", 700, 1600, 3, 7, "PASSIVE - You gain +20% additional Movement Speed after leaving the Fountain. This effect lasts 7s.", 'ItemImages/travelers-shoes.png', 'Movement Speed, magPow, MP5', 2, 25, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, 22, NULL, NULL, 22, NULL),
("Hidden Dagger", 700, 700, 1, 8, "£", 'ItemImages/hidden-dagger.jpg', 'physPow, ', 1, 15, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Short Sword", 650, 1350, 2, 8, "£", 'ItemImages/short-sword.jpg', 'physPow, ', 1, 25, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Deathbringer", 1650, 3000, 3, 8, "PASSIVE - Critical Strike bonus damage dealt is increased by 30%.", 'ItemImages/deathbringer.jpg', 'physPow, crit, dmgPercInc, ', 1, 50, NULL, NULL, NULL, NULL, 25, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Rage", 1150, 2500, 3, 8, "PASSIVE - Killing or getting an assist on an enemy god gives you 1 stack. Each stack provides 3% Critical Strike Chance. Stacks are permanent and stack up to 5 times.", 'ItemImages/rage.jpg', 'physPow, crit, stack', 1, 30, NULL, NULL, NULL, NULL, 30, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Evolved Rage", 0, 2500, 3, 8, "£", 'ItemImages/rage.jpg', 'physPow, crit, evolve', 1, 30, NULL, NULL, NULL, NULL, 45, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Malice", 1300, 2650, 3, 8, "PASSIVE - Successfully Hitting an Enemy God with a Critical Strike will subtract 3s from all of your abilities currently on Cooldown, except your Ultimate ability. This effect can only happen once every 5s.", 'ItemImages/malice.jpg', 'physPow, crit, cdr, ', 1, 40, NULL, NULL, NULL, NULL, 25, null, NULL, NULL, NULL, null, NULL, 10, NULL, NULL, NULL),


("Spiked Gauntlet", 600, 60, 1, 9, "£", 'ItemImages/spiked-gauntlet.jpg', 'physPow, physLs, ', 1, 5, NULL, 7, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Cursed Gauntlet", 800, 1400, 2, 9, "£", 'ItemImages/cursed-gauntlet.jpg', 'physPow, physLs, ', 1, 20, NULL, 10, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Bound Gauntlet", 450, 1050, 2, 9, "£", 'ItemImages/bound-gauntlet.jpg', 'physPow, physLs, ', 1, 15, NULL, 10, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Soul Eater", 1050, 2100, 3, 9, "PASSIVE - Your abilities heal you for 5% of damage dealt. Each time anything dies within 80 units you gain a stack. Gods, Large Jungle monsters and Bosses provide 5 stacks. At 75 Stacks Soul Eater Evolves, gaining 15 Physical Power, 5% Physical Lifesteal, and causing abilities to heal you for 20% of damage dealt.", 'ItemImages/soul-eater.jpg', 'physPow, physLs, cdr, physPenPerc, abilityProc, stack, ', 1, 20, NULL, 10, 10, NULL, NULL, null, NULL, NULL, NULL, null, NULL, 10, NULL, NULL, NULL),
("Evolved Soul Eater", 0, 2100, 3, 9, "PASSIVE - Your abilities heal you for 20% of the damage dealt to targets.", 'ItemImages/evolved-soul-eater.png', 'physPow, physLs, cdr, physPenPerc, abilityProc, evolve', 1, 35, NULL, 15, 10, NULL, NULL, null, NULL, NULL, NULL, null, NULL, 10, NULL, NULL, NULL),
("Devourer's Gauntlet", 900, 2300, 3, 9, "PASSIVE - Killing an enemy god or minion gives you stacks of +.5 Physical Power and +.2% Physical Lifesteal. You receive 5 stacks for a god kill and 1 stack for a minion kill. Stacks up to 70 times.", 'ItemImages/devourers-gauntlet.jpg', 'physPow, physLs, stack, ', 1, 30, NULL, 15, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Evolved Devourer's Gauntlet", 0, 2300, 3, 9, "£", 'ItemImages/devourers-gauntlet.jpg', 'physPow, physLs, evolve, ', 1, 65, NULL, 29, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("Bloodforge", 1400, 2800, 3, 9, "PASSIVE - Killing an enemy god forges a shield from their blood with Health equal to 200 + 10 per Player Level for 20s. While the Blood Shield is active you gain +10% movement speed.", 'ItemImages/bloodforge.jpg', 'physPow, physLs, shld, mvSpd, ', 1, 75, NULL, 15, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),



("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),
("", , , 3, , "£", 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL),


('', , , 3, , '£', 'ItemImages/', '', 1, NULL, NULL, NULL, NULL, NULL, NULL, null, NULL, NULL, NULL, null, NULL, NULL, NULL, NULL, NULL);